services:
  php_laravel:
    build: ./backend
    container_name: php_laravel
    hostname: "php"
    volumes:
      - ./backend:/var/www/html
      - ./backend/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./backend/local.ini:/usr местных/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_laravel
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
      - SESSION_DRIVER=cookie 
      - SESSION_DOMAIN=${SESSION_DOMAIN}
    ports:
      - "8000:8000"
    depends_on: 
      - mysql_laravel
    #networks:
    #   - laravelnetwork

  mysql_laravel:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql_laravel
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "36306:3306"
    volumes:
      - mysql-logs:/var/log/mysql
      - ./database/setupdb.sql:/docker-entrypoint-initdb.b/01-setupdb.sql
      - ./database/data:/var/lib/mysql
      - ./database/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicite-defaults-for-timestamp=ON"
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 6  
    #networks:
    #  - laravelnetwork

  npm:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: node:lts-alpine3.22
    working_dir: /var/www/app
    container_name: npm_dev
    hostname: "npm"
    volumes:
      - ./frontend:/var/www/app
      - /var/www/app/node_modules  #ignore node_modules dir when copy
    ports:
      - "5173:80"
    #networks:
    #  - laravelnetwork
volumes:
  mysql-logs:
#networks:
  # a networkte allows the various containers to communicate with each other
#  laravelnetwork:
#    driver: bridge
